apiVersion: v1
kind: ReplicationController
metadata: 
  name: frontend
  labels: 
    name: frontend
spec: 
  replicas: 3
  selector: 
    name: frontend
  template: 
    metadata: 
      labels: 
        name: frontend
    spec: 
      containers: 
      - name : frontend
        image: kubeguide/guestbook-php-frontend
        ports: 
        - containerPort: 80